import { FormEvent, useState } from "react"; import { supabase } from "./lib/supabase";

const services=[{number:"01",title:"Digital Products",text:"We design and build purposeful digital products that solve real problems and create measurable value."},{number:"02",title:"Web & Software",text:"Fast, scalable web experiences and software engineered for reliability, accessibility and growth."},{number:"03",title:"Technology Solutions",text:"Practical technology strategy and implementation that helps organizations operate smarter."}];
const values=["Human-centered design","Reliable engineering","Performance by default","Built to scale"];
const Arrow=()=> <span aria-hidden="true">↗</span>;

export default function App(){
 const [menuOpen,setMenuOpen]=useState(false); const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle"); const [website,setWebsite]=useState("");
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); if(status==="sending") return; setStatus("sending"); const form=e.currentTarget; const data=new FormData(form); const payload={name:String(data.get("name")||"").trim(),email:String(data.get("email")||"").trim(),message:String(data.get("message")||"").trim()}; if(website.trim()){setStatus("success");form.reset();return;} if(!payload.name||!payload.email||!payload.message){setStatus("error");return;} if(!supabase){console.error("Supabase is not configured.");setStatus("error");return;} const {error}=await supabase.from("contact_messages").insert(payload); if(error){console.error("Contact submission failed:",error);setStatus("error");return;} form.reset(); setStatus("success");};
 return <div className="site">
  <header className="nav"><a className="brand" href="#top" onClick={()=>setMenuOpen(false)}><span className="brandMark">C</span><span>Con Universe</span></a><button className="menuButton" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>☰</button><nav className={menuOpen?"navLinks open":"navLinks"}><a href="#work" onClick={()=>setMenuOpen(false)}>What we do</a><a href="#about" onClick={()=>setMenuOpen(false)}>About</a><a href="#process" onClick={()=>setMenuOpen(false)}>Process</a><a className="navCta" href="#contact" onClick={()=>setMenuOpen(false)}>Start a project <Arrow/></a></nav></header>
  <main id="top">
   <section className="hero"><div className="heroGlow"/><div className="heroCopy"><p className="eyebrow">DIGITAL PRODUCTS · TECHNOLOGY · GROWTH</p><h1>Technology that moves <em>business</em> forward.</h1><p className="heroText">Con Universe creates modern digital products and technology solutions for ambitious people, businesses and communities.</p><div className="heroActions"><a className="button primary" href="#contact">Build with us <Arrow/></a><a className="textLink" href="#work">Explore our capabilities <Arrow/></a></div></div><div className="heroCard"><div className="orb"><span>CU</span></div><div className="cardLabel">CON UNIVERSE</div><p>Ideas into products.<br/>Products into impact.</p><div className="cardLine"/></div></section>
   <section className="stats"><div><strong>01</strong><span>Focused on outcomes</span></div><div><strong>02</strong><span>Designed for real people</span></div><div><strong>03</strong><span>Ready for what is next</span></div></section>
   <section id="work" className="section"><div className="sectionIntro"><p className="eyebrow">CAPABILITIES</p><h2>From first idea to <span>real-world product.</span></h2><p>We combine product thinking, engineering and thoughtful design to turn complex challenges into simple experiences.</p></div><div className="serviceGrid">{services.map(s=><article className="service" key={s.number}><span>{s.number}</span><h3>{s.title}</h3><p>{s.text}</p><a href="#contact">Learn more <Arrow/></a></article>)}</div></section>
   <section id="about" className="darkSection"><div className="split"><div><p className="eyebrow">WHY CON UNIVERSE</p><h2>Small enough to care. <span>Serious enough to deliver.</span></h2></div><div><p className="largeText">Technology should feel useful, not complicated. Our approach is grounded in clarity, strong engineering and a deep respect for the people who use what we build.</p><div className="valueList">{values.map((v,i)=><div key={v}><span>0{i+1}</span>{v}</div>)}</div></div></div></section>
   <section id="process" className="section process"><div className="sectionIntro"><p className="eyebrow">OUR PROCESS</p><h2>A clear path from <span>idea to impact.</span></h2></div><div className="processGrid">{["Discover","Design","Build","Launch"].map((x,i)=><div className="processItem" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Understand the opportunity, users and business goals.","Shape the experience, architecture and visual direction.","Build cleanly, test thoroughly and iterate quickly.","Release confidently, measure results and keep improving."][i]}</p></div>)}</div></section>
   <section id="contact" className="contact"><div><p className="eyebrow">LET'S TALK</p><h2>Have an idea worth building?</h2><p>Tell us what you are working on. We will turn the conversation into a clear next step.</p></div><form onSubmit={submit}><label>Name<input required name="name" maxLength={120} autoComplete="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" maxLength={320} autoComplete="email" placeholder="you@company.com"/></label><label>Project brief<textarea required name="message" maxLength={5000} rows={5} placeholder="What would you like to build?"/></label><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div><button className="button primary" disabled={status==="sending"}>{status==="sending"?"Sending…":"Send enquiry"} <Arrow/></button>{status==="success"&&<p className="success" role="status">Thanks — your enquiry has been received.</p>}{status==="error"&&<p className="error" role="alert">We could not send your enquiry. Please check your details and try again.</p>}</form></section>
  </main>
  <footer><div className="footerBrand"><span className="brandMark">C</span><span>Con Universe</span></div><p>Digital products and technology solutions.</p><div>© {new Date().getFullYear()} Con Universe. All rights reserved.</div></footer>
 </div>
}